version: "3.4"

services:
  redis-server:
    image: "redis"
  conduitbackend:
    image: conduitbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
